### ISSUE TITLE
Redesign: Homepage

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/pressfreedomtracker.us#1165]
- [x] Header and navigation - @chigby #1182 
- [x] Footer (includes contact block and mailing list signup)
- [x] Basic search bar - @chigby #1184 
- [x] Hero w/ charts (maybe?)
- [x] Blog post teaser - @chigby #1185 
- [x] Incident teaser (col design)
- [x] Categories block - @chigby 

[Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=4120%3A82741)
