### ISSUE TITLE
Incident detail page

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1187]
This ticket is for building and piecing together the components of the incident page _except_ for stream field blocks, which are specified in #1186.

You can see example templates incident pages in [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3565%3A41473).

The components needed on the page include:

- [ ] Incident details table (new component, [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A61121)) - @SaptakS - #1211
- [ ] Sources table (new component, [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A61121)) - @SaptakS - #1211
- [ ] Incidents from same event table (new component, [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A61121)) - @SaptakS - #1211
- [x] Page title (use component from [style guide](https://redesign.pressfreedomtracker.us/styleguide/#typography))
- [x] Tags (use component from [style guide](https://redesign.pressfreedomtracker.us/styleguide/#buttons))
- [ ] Introduction (new component, [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A60362), may require new field)
- [ ] Cover photo/video (new component, [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A72698))
- [ ] Related incidents (see example in [Figma template](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3565%3A41473))

**Comment by SaptakS** [comment]
I have started working on the list table component as shown in the [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A61121), that has similar styles for incident details, sources table and other tables in both incident detail page and blog detail page.

**Comment by urlsangel** [comment]
Hi @harrislapiroff 👋

I started working on this project with Torchbox yesterday, so I'm just orienting myself to various bits.

I have a quick question for you -  I’m getting a 403 when accessing style guide links from the description of this issue.

The initial request took me to Github to authorise - which I did - but subsequent visits return a 403, so do i need to granted access somewhere else?

<img width="826" alt="Screenshot 2022-01-26 at 13 39 22" src="https://user-images.githubusercontent.com/560463/151180419-d81ad697-02e3-4372-9100-eadb164a27ea.png">

**Comment by harrislapiroff** [comment]
Hi @urlsangel! I think we need to add you to the vouch allow list. Pinging @maeve-fpf

**Comment by harrislapiroff** [comment]
In the meantime, I've added you as a contributor to the repo

**Comment by urlsangel** [comment]
Hi @harrislapiroff @SaptakS 

I've been tasked with looking at this issue next, and I have a few questions if you can help? (I'm in the UK, and will be offline from 3pm GMT today, so no worries if you respond later, I'll be back online tomorrow morning).

Firstly, am I at risk of duplicating any effort from @SaptakS if I start on this issue? There's a comment from a couple of weeks ago that suggests I might?

https://github.com/freedomofpress/pressfreedomtracker.us/issues/1187#issuecomment-1010027184

Secondly, I've been working on this issue as well: https://github.com/freedomofpress/pressfreedomtracker.us/issues/1186

Should I continue on the same branch, as there is a new django migration present already, or would you prefer this work to be on a separate branch, and we figure out migrations later?

Finally, with regard to these components, can you confirm where the data is coming from? I've put assumptions next to each of them:

 - Incident details table - made up of multiple page metadata fields? If so, is there a definitive list of these?
 - Sources table - inline panel named `links`?
 - Incidents from same event table - a query on incident pages filtered on same event?
 - Related incidents - the `get_related_incidents` method?

**Comment by urlsangel** [comment]
> In the meantime, I've added you as a contributor to the repo

Thanks @harrislapiroff!

**Comment by urlsangel** [comment]
@harrislapiroff 

>  Cover photo/video (new component, Figma)

Should this component use the page's `teaser_image` field, or should a new field be added to the model?

**Comment by harrislapiroff** [comment]
@urlsangel Let's use the existing `teaser_image` field. I don't think we've run into a scenario where the editors want a different teaser image from cover image.

**Comment by harrislapiroff** [comment]
@urlsangel for the other questions, Saptak has actually been working on all of these items. @SaptakS would you update @urlsangel on the state of those items? (We've going to kick sources and incidents from the same event to other tickets for the moment.)

**Comment by SaptakS** [comment]
Sure. @urlsangel as @harrislapiroff mentioned, we have decided to not implement sources and incidents from the same event features right now. I have created separate tickets for both of them so that we can track those separately. And I am working on the incident details table right now. 

Any thing else in this ticket should be open to be worked on. Some of them are already implemented style wise and just needed to be pulled from the styleguide and added in the appropriate places.

**Comment by urlsangel** [comment]
@SaptakS 

Great, I've been working on the other components, so we're aligned!

@harrislapiroff 

I'm still not able to access the style guide, do you know if that's possible to fix?

Original comment here: https://github.com/freedomofpress/pressfreedomtracker.us/issues/1187#issuecomment-1022244593

**Comment by chigby** [comment]
Potential mismatch between our data and the design: the image caption.

![image](https://user-images.githubusercontent.com/561931/152051244-ba76bb21-8829-4f15-9305-524351eea430.png)

The image caption field in the incident model is rich text, and the attribution is a separate field. Rich text will be rendered as block elements. The design has the caption text inline with the attribution.

**Comment by chigby** [comment]
I also just realized that the image caption field mentioned above, in spite of being rich text, has a character limit of 255, which can lead to some counterintuitive validation errors:
![image](https://user-images.githubusercontent.com/561931/152064217-bf5f0590-9240-49e1-bcb3-95110853441b.png)

**Comment by chigby** [comment]
One more note: pages can have a `primary_video` field. Is this something that's used currently, or want to use on the detail page redesign? I tried setting it to a youtube video locally and the embed was blocked by the CSP.
