### ISSUE TITLE
Database page, part 1

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1216]
See: [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=4410%3A107575)

The `IncidentIndexPage` should be updated to support all the functionality in the mockup.

For part 1, don't bother with React components for the sidebar, just use basic native HTML controls. We will swap these out later for react components. Leave largely unstyled for now.

- [x] Horizontal incident cards and list #1217 @chigby 
- [x] Filters sidebar #1218 - @urlsangel 
- [x] Header and layout #1219 - @chigby 
- [x] Integration #1220

**Comment by harrislapiroff** [comment]
This is done
