### ISSUE TITLE
Database page filters native HTML usability

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1282]
- [x] Eliminate raw id fields (Addressed by #1277)
- [x] Add date selectors (Fixed in #1284)
- [x] "Clear all" button should work (Fixed in #1284)
